import { ProjetoEngenharia } from "./types";

export const ICOMProject: ProjetoEngenharia = {
  id: "prj_icom_01",
  categoria: "HOSPITAIS",
  titulo: "Instituto Couto Maia - ICOM",
  descricao:
    "Unidade de referência da Bahia especializada exclusivamente no tratamento de doenças transmissíveis de alta complexidade.",
  descricaoCompleta:
    "O Instituto Couto Maia (Icom) Localizado em Cajazeiras e inaugurado em julho de 2018, a unidade é referência em infectologia no Brasil. Com infraestrutura de ponta, inclui leitos de UTI e diagnósticos avançados por imagem.",

  status: "Concluído",
  relevancia: 5.0,
  cliente: "SESAB",
  localizacao: "Bairro de Cajazeiras, Salvador – BA.",
  periodo: {
    duracao: "16 meses",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0dumsle7u07muar5dw4cy",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8vylcoo07mujx782tjk",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8tslhdi07nagy5him94",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8qqlco907mus7xhe1vn",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8o7lhdb07narzoeazj5",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8krlhd407nayqrl0g07",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8hjlcnv07muyz6ctk65",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8f9lhcx07na81qgkfp2",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c8colhcq07navpvr8p1s",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c89tlcno07muefq0vl44",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c87mlcnh07muvo10ebal",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkd0c849lhcj07na822w93pr",
  ],
  especificacoes: {
    "Área Construida": "19.605,56 m²",
    "N° de Leitos": 120,
    "N° Unidades de Terapia Intensiva": ["10 adultos", "10 infantis"],
    "Centros Cirurgicos": 2,
  },
};

export const CleristonAndradeProject: ProjetoEngenharia = {
  id: "prj_cleriston_05",
  categoria: "HOSPITAIS",
  titulo: "Hospital Clériston Andrade",
  descricao:
    "Projeto hospitalar de grande porte, com ampliação e modernização da infraestrutura de atendimento à saúde.",
  descricaoCompleta:
    "Hospital Geral Clériston Andrade - HGCA II. A ampliação do complexo hospitalar Clériston Andrade, em Feira de Santana, compreende uma estrutura de alta complexidade com 8.000 m² de área construída. Executada em apenas 14 meses, a obra entregou uma das unidades mais tecnológicas do estado.",
  status: "Concluído",
  relevancia: 3.8,
  cliente: "SESAB",
  localizacao:
    "Avenida Eduardo Fróes da Mota, S/N, Bairro 35º BI, Feira de Santana - BA",
  periodo: {
    duracao: "14 meses",
    conclusao: "2023-05",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkdhgm2aytwk07murengz816",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkdhgljlywmm07nasmvo97e4",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkdhglr4ywn007na6taig36c",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkdhglu8ytwd07mu82cfveeo",
  ],
  especificacoes: {
    "Área Construída": "24.000 m²",
    "N° de UTIs": 40,
    "Salas de Cirurgia": 11,
    "Salas de Tomografia": 2,
    "Salas de Raios-X": 2,
    "Sala de Ressonância": 1,
  },
};



export const HospitalItaberabaProject: ProjetoEngenharia = {
  id: "prj_itaberaba",
  categoria: "HOSPITAIS",
  titulo: "Hospital Regional de Itaberaba",
  descricao:
    "Reforma integral e ampliação da infraestrutura hospitalar para atendimento de alta complexidade na Chapada Diamantina.",
  descricaoCompleta:
    "O projeto contemplou a adequação total do espaço físico e a ampliação da unidade, que agora conta com mais de 100 leitos, incluindo UTIs adulto e pediátrica. A obra focou na modernização das salas de cirurgia, implantação de um moderno centro de bioimagem (CT e Raio-X) e reestruturação das enfermarias. Esta intervenção foi fundamental para descentralizar a saúde no estado, permitindo que o hospital passasse a oferecer serviços de urgência, emergência e cirurgias eletivas para Itaberaba e outros 11 municípios da região.",
  status: "Concluído",
  relevancia: 2.9,
  cliente: "Governo do Estado da Bahia - SESAB",
  localizacao: "Itaberaba - BA",
  periodo: {
    duracao: "22 meses",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabfi26t0b07n2ccoj9blz",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabfkf6t0i07n2bl5ivjj9",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabdnt6sy707n20fii97u8",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabdr46whw07lpvzolf4m8",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabdu26sye07n26a08utyx",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrabdwn6wi307lpaqukjrzp",
  ],
  especificacoes: {
    "Área Construída": "5.297,54 m²",
    Enfermaria: "60 leitos",
    "UTI-Unidade de Terapia": "10 leitos",
    "Urgência/emergência": "16 leitos",
    "Centro Cirúrgico": "04 leitos",
    Tomografia: "1",
    "Raio-X": "1",
  },
};

export const HospitalItabunaProject: ProjetoEngenharia = {
  id: "prj_itabuna",
  categoria: "HOSPITAIS",
  titulo: "Hospital de Base Luís Eduardo Magalhães",
  descricao:
    "Elaboração de projetos e execução de obras para ampliação e reforma integral do Hospital de Base, modernizando a infraestrutura para alta complexidade e emergência..",
  descricaoCompleta:
    "O projeto consistiu na contratação integrada para o desenvolvimento dos projetos básicos e executivos, seguidos pela execução física das obras de reforma e expansão do Hospital de Base Luís Eduardo Magalhães. A intervenção focou na reestruturação completa do pronto-socorro, na criação de novas alas de internamento e na modernização do centro cirúrgico. Com a ampliação, a unidade recebeu reforço estrutural para comportar novos leitos de UTI e unidades de cuidados intermediários, além de uma readequação total dos fluxos hospitalares conforme as normas da RDC 50 da ANVISA. O empreendimento visou não apenas a melhoria estética, mas a eficiência operacional necessária para atender a demanda crescente da macrorregião Sul da Bahia, integrando sistemas avançados de climatização, gases medicinais e instalações elétricas de suporte crítico.",
  status: "Concluído",
  relevancia: 4,
  cliente: "Governo do Estado da Bahia - SESAB",
  localizacao: "Município de Itabuna – Bahia",
  periodo: {
    duracao: "26 meses",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfiov8si007lpriijxsl2",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfidi8pyf07n2obf8ikkc",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfim08q0i07n2vj6u6ipg",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfiax8sel07lph3ro25qa",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfi388pw507n28mv7ix6a",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfijk8sgv07lp3o9z0rtu",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfigh8sfq07lpvrzxkbnl",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfi8a8pxa07n2eq0ei050",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfi5r8sck07lpix920vjh",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfi098scb07lpv215pxg8",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfj078skz07lp4bvscsc1",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfhxq8sa807lppnzl5v7p",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfis38si907lp33vpmzaw",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfhuo8pu207n2057xzpkc",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfhrs8psu07n2qhjwjtxd",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfhox8s7707lp5ve7lmsa",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfhl98s6w07lpgu8mpume",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfj308q6k07n2eaetr523",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfixj8q5f07n2wqi49ud4",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkrcfiv78sik07lpt6kbxyod",
  ],
  especificacoes: {
    "Área Construída": "9.475,43 m²",
    "N° de UTIs": "N° de UTIs leitos",
    "Centro Cirúrgico": "6 leitos",
    "Sala Vermelho": "3 leitos",
    "Sala Amarela": "4 leitos",
    "Sala de Observação": "12 leitos",
    Outros: ["Ambulatório", "Tomografia", "Raio-X"],
  },
};


export const HospitalRegionalLitoralNorte: ProjetoEngenharia = {
  id: "prj_hospital_regional_litoral_norte",
  categoria: "HOSPITAIS",
  titulo: "Hospital Regional do Litoral Norte - Alagoinhas-BA",
  descricao: "Não Informado",
  descricaoCompleta: "Não Informado",
  status: "Em andamento",
  relevancia: 1,
  cliente: "CONDER",
  localizacao: "Município de Itabuna – Bahia",
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bbuqppdg08loda4hgw3r",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bbx7ph9q07loedfs290c",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bbzhppdn08lovhk5diop",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bc2bph9z07loi2zvobq4",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bc59ppdu08lod9oyig08",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bc80pha607lohh8fea3x",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcacppe208lohpi3ta5n",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcdephad07lo1i3lggtd",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bbruph9j07lotfx7hpmt",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bbruph9j07lotfx7hpmt",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcgappe908lopcoq0xc8",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcifphak07loc2d8ctuv",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bckmppeg08lor8297os8",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcmyphar07log7ylum8s",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcphphay07lonfd84hw4",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcsbppen08lokzbb5fn7",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcvfppeu08lo3ggj7t2z",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bcxhphbc07lovkwef5a6",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bd0eppf108loxtdf9ho3",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bd39phbj07lo4lg2srmu",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bd5nppf808lojloxn669",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bd8uppff08loj2ao67oo",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bdb7ppfm08loyhcq9ba7",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bdeaphbq07lo2fqy2ik1",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bdgbphbx07lo7fys8k8x",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz7bdjcppft08lomtns6w9z",
  ],
  especificacoes: {
    "Área Construída": "23.262,09m²",
    "N° de UTIs": "30 leitos de UTI",
    "N° de Enfermaria": "150 leitos de Enfermarias",
    "Parto Normal": "3 leitos",
    "Salas de Cirurgia": "5 + 1 de Hemodinâmica",
    "Salas de Imagenologia": "2 Tomógrafos, 2 Raios X, 1 Ressonância",
    Quimioterapia: "12 poltronas",
    Radiologia: "Acelerador Linear e Braquiteriapia",
  },
};


export const HospitalDrJoseBorbaSanta: ProjetoEngenharia = {
  id: "prj_hospital_dr_jose_borba_santa",
  categoria: "HOSPITAIS",
  titulo: "Hospital Dr. José Borba–Santa Maria da Vitória-BA ",
  descricao: "A obra de ampliação do hospital foi concluída com alto padrão de qualidade, contemplando no pavimento térreo a execução de posto de enfermagem, áreas de esterilização, armazenagem, desinfecção química, centro cirúrgico, sala de parto, unidades de tratamento intensivo (UTI), setores de descontaminação e lavagem, além de circulações internas funcionais com rampas de acessibilidade e elevadores interligando os dois pavimentos, em conformidade com as normas técnicas vigentes. ",
  descricaoCompleta: "A obra de ampliação do hospital foi concluída com alto padrão de qualidade, contemplando no pavimento térreo a execução de posto de enfermagem, áreas de esterilização, armazenagem, desinfecção química, centro cirúrgico, sala de parto, unidades de tratamento intensivo (UTI), setores de descontaminação e lavagem, além de circulações internas funcionais com rampas de acessibilidade e elevadores interligando os dois pavimentos, em conformidade com as normas técnicas vigentes. No primeiro pavimento, foram implantadas novas enfermarias, sendo 30 leitos destinados à clínica cirúrgica e outros 30 leitos à clínica geral e psiquiatria, ampliando significativamente a capacidade assistencial da unidade. As intervenções externas incluíram a execução de iluminação, paisagismo, passeios acessíveis, adequação dos acessos ao hospital existente e organização dos estacionamentos, resultando em um complexo hospitalar plenamente funcional, seguro e entregue conforme os projetos aprovados, com elevado padrão técnico e construtivo",
  status: "Concluído",
  relevancia: 1,
  cliente: "PREFEITURA(CONVÊNIO SESAB)",
  localizacao: "Município de Santa Maria da Vitória – BA",
  periodo: {
    duracao: "24 meses",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7f6p7rf08log32gv1jz",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7imp7ro08losbm5itaj",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7imp7ro08losbm5itaj",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7lzp7rv08lo6valxxix",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efe3ozyl07lomjjv6ewy",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efh9ozys07lo5q7ukwe0",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e6sep7qh08lo0gnol581",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e6v3ozug07loyoox4qcn",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e6yap7qq08lonnxh0ea0",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e71gozun07loqq70rsis",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e74eozuu07lo720zhmup",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e779p7qz08loe3g1ctjr",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7acp7r608lohri5s2xe",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7d0ozv307lolrj3eem5",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7ofp7s208lomnujrqh9",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5e7qyozvt07log2wjrjbm",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efkbp7vf08loobenwtho",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efmuozyz07lorgd5uh95",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efprp7vm08lo6ctxjmcx",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efs8p7vt08loxrsfcp0v",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efv3ozz607lowusnkrfq",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efxlozzd07lonicis45i",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5efzwp7w008lod5fzzxao",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5eg28ozzk07locw1hxj5f",
  ],
  especificacoes: {
    "Área Construída": "4.662,24m²",
    "N° de UTIs": "10 leitos de UTI",
    "N° de Enfermaria": "60 leitos de Enfermarias",
    "Parto Normal": "3 leitos",
    "Salas de Cirurgia": "5 salas",
  },
};

export const ObrasComplementaresMaternidadeJoaoBatista: ProjetoEngenharia = {
  id: "prj_obras_maternidade_joao_batista",
  categoria: "HOSPITAIS",
  titulo: "Obras complementares maternidade João Batista Caribé Salvador-BA",
  descricao:
    "Este projeto abrange a execução de uma obra hospitalar de alta complexidade, combinando estética moderna e funcionalidade rigorosa.",
  descricaoCompleta:
    "Este projeto abrange a execução de uma obra hospitalar de alta complexidade, combinando estética moderna e funcionalidade rigorosa. O escopo da obra incluiu o acabamento de superfícies metálicas e a instalação de brises em alumínio, garantindo eficiência térmica e design contemporâneo. No âmbito clínico, destaca-se a implementação de blindagens e elementos construtivos de proteção para a sala de Raio-X, além da construção e adequação de ambientes críticos como salas de ultrassonografia (USG), acolhimento, higienização e áreas para instalação de autoclave. A estrutura é complementada por sistemas vitais de engenharia, incluindo uma Central de Gases Medicinais, câmaras frigoríficas e instalações completas de climatização, assegurando um ambiente seguro e tecnicamente otimizado para operações de saúde.",
  status: "Concluído",
  relevancia: 1,
  cliente: "Governo do Estado da Bahia - CONDER",
  localizacao:
    "Av. Afrânio Peixoto (Avenida Suburbana), s/n.- Coutos, Salvador - BA",
  periodo: {
    duracao: "4 meses",
  },
  imagens: [
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vq6bp45g07lok2dlpg47",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vq8ypbtd08lomniy4a7k",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqc0p45n07lon5vslcgp",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqe2p45u07lofvjjjznt",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqh1pbtk08loibsld3xi",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqjlp46107lo20zye29y",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqmep46807loypz5yosf",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqp7pbtr08lof2igumop",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqripbty08loboa6fkok",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqufpbu508lof70ta4mx",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vqx2p46f07lohfungysl",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vr01pbuc08louvp7qwer",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vr31p46m07lo1k1dcx5y",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vr6apbuj08loztonpzi3",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vr8vp46t07lo2u1pk2aj",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrb1pbuq08lo4ikw6typ",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrdtp47007locnpabim0",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrgup47707loyf2bca0b",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrjkp47e07lobiplzuzw",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrmrpbux08loz69sa3k1",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrp1pbv408loa0og2w9n",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrs3pbvb08lo6yvl89jl",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vruwp47l07loo9arfkmv",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vrxmp47s07lox445oees",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vs0lpbvi08lofztb89eh",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vs3ip47z07lou7dxkht0",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vs6gpbvp08lok6owtp50",
    "https://us-west-2.graphassets.com/cmkc1ejod2bpe07lper075xkw/output=format:jpg/cmkz5vs8xp48607loblykrvex",
  ],
  especificacoes: {
    "Área ampliada": "440m²",
    "N° de UTI Neonatal": "10 leitos",
  },
};