import { ProjetoEngenharia } from "./types";

export const ICOMProject: ProjetoEngenharia = {
  id: "prj_icom_01",
  categoria: "Hospitais",
  titulo: "Instituto Couto Maia - ICOM",
  descricao:
    "Unidade de referência da Bahia especializada exclusivamente no tratamento de doenças transmissíveis de alta complexidade.",
  descricaoCompleta:
    "O Instituto Couto Maia (Icom) Localizado em Cajazeiras e inaugurado em julho de 2018, a unidade é referência em infectologia no Brasil. Com infraestrutura de ponta, inclui leitos de UTI e diagnósticos avançados por imagem.",

  status: "Concluído",
  relevancia: 5.0,
  cliente: "SESAB",
  localizacao: "Bairro de Cajazeiras, Salvador – BA.",
  periodo: {
    duracao: "16 meses",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788196/Metro/srhw6asequfysh6uurit.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787947/Metro/hh274w6u29reyvywxqyn.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788325/Metro/ym2c7xk0herlzm1t2ypz.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788382/Metro/pmc2uyivirnf9dzhpuvh.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788185/Metro/kplylfioswjibo37xjfj.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787925/Metro/vwad15sxv5asmnmfiefa.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788145/Metro/eosm1xsjnbzwkgubcscs.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788107/Metro/zggihlhscwnot120dof5.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788244/Metro/xgjq9zbmfxcftxtmaqx6.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787909/Metro/aruqt6edhrqfkaohoij1.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788327/Metro/awdh8pbpjcxyehhveqy4.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787933/Metro/ptbocppcskheydtjkb8k.jpg",
  ],
  especificacoes: {
    "Área Construida": "19.605,56 m²",
    "N° de Leitos": 120,
    "N° Unidades de Terapia Intensiva": ["10 adultos", "10 infantis"],
    "Centros Cirurgicos": 2,
  },
};

export const CleristonAndradeProject: ProjetoEngenharia = {
  id: "prj_cleriston_05",
  categoria: "Hospitais",
  titulo: "Hospital Clériston Andrade",
  descricao:
    "Projeto hospitalar de grande porte, com ampliação e modernização da infraestrutura de atendimento à saúde.",
  descricaoCompleta:
    "Hospital Geral Clériston Andrade - HGCA II. A ampliação do complexo hospitalar Clériston Andrade, em Feira de Santana, compreende uma estrutura de alta complexidade com 8.000 m² de área construída. Executada em apenas 14 meses, a obra entregou uma das unidades mais tecnológicas do estado.",
  status: "Concluído",
  relevancia: 3.8,
  cliente: "SESAB",
  localizacao:
    "Avenida Eduardo Fróes da Mota, S/N, Bairro 35º BI, Feira de Santana - BA",
  periodo: {
    duracao: "14 meses",
    conclusao: "2023-05",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788033/Metro/gl9cmzmywredxw1zyf6c.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788385/Metro/uf5gwyqdli3y2zkguu2v.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788348/Metro/fwbrtxlpg0i7ttgo8uem.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788257/Metro/ywdlqcmhko9enqfa55qt.jpg",
  ],
  especificacoes: {
    "Área Construída": "24.000 m²",
    "N° de UTIs": 40,
    "Salas de Cirurgia": 11,
    "Salas de Tomografia": 2,
    "Salas de Raios-X": 2,
    "Sala de Ressonância": 1,
  },
};



export const HospitalItaberabaProject: ProjetoEngenharia = {
  id: "prj_itaberaba",
  categoria: "Hospitais",
  titulo: "Hospital Regional de Itaberaba",
  descricao:
    "Reforma integral e ampliação da infraestrutura hospitalar para atendimento de alta complexidade na Chapada Diamantina.",
  descricaoCompleta:
    "O projeto contemplou a adequação total do espaço físico e a ampliação da unidade, que agora conta com mais de 100 leitos, incluindo UTIs adulto e pediátrica. A obra focou na modernização das salas de cirurgia, implantação de um moderno centro de bioimagem (CT e Raio-X) e reestruturação das enfermarias. Esta intervenção foi fundamental para descentralizar a saúde no estado, permitindo que o hospital passasse a oferecer serviços de urgência, emergência e cirurgias eletivas para Itaberaba e outros 11 municípios da região.",
  status: "Concluído",
  relevancia: 2.9,
  cliente: "Governo do Estado da Bahia - SESAB",
  localizacao: "Itaberaba - BA",
  periodo: {
    duracao: "22 meses",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788393/Metro/nma2gapopkxy9lgvaiuh.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788078/Metro/zq49iouggykqsq46sc2w.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787936/Metro/mksd1mjryuqjdijouij1.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788148/Metro/kftt7a52ih2ihmzjgv8m.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787977/Metro/afpjr2g6mg7zncszbkw3.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788063/Metro/ymwfr7qbwwb6laprcchi.jpg",
  ],
  especificacoes: {
    "Área Construída": "5.297,54 m²",
    Enfermaria: "60 leitos",
    "UTI-Unidade de Terapia": "10 leitos",
    "Urgência/emergência": "16 leitos",
    "Centro Cirúrgico": "04 leitos",
    Tomografia: "1",
    "Raio-X": "1",
  },
};

export const HospitalItabunaProject: ProjetoEngenharia = {
  id: "prj_itabuna",
  categoria: "Hospitais",
  titulo: "Hospital de Base Luís Eduardo Magalhães",
  descricao:
    "Elaboração de projetos e execução de obras para ampliação e reforma integral do Hospital de Base, modernizando a infraestrutura para alta complexidade e emergência..",
  descricaoCompleta:
    "O projeto consistiu na contratação integrada para o desenvolvimento dos projetos básicos e executivos, seguidos pela execução física das obras de reforma e expansão do Hospital de Base Luís Eduardo Magalhães. A intervenção focou na reestruturação completa do pronto-socorro, na criação de novas alas de internamento e na modernização do centro cirúrgico. Com a ampliação, a unidade recebeu reforço estrutural para comportar novos leitos de UTI e unidades de cuidados intermediários, além de uma readequação total dos fluxos hospitalares conforme as normas da RDC 50 da ANVISA. O empreendimento visou não apenas a melhoria estética, mas a eficiência operacional necessária para atender a demanda crescente da macrorregião Sul da Bahia, integrando sistemas avançados de climatização, gases medicinais e instalações elétricas de suporte crítico.",
  status: "Concluído",
  relevancia: 4,
  cliente: "Governo do Estado da Bahia - SESAB",
  localizacao: "Município de Itabuna – Bahia",
  periodo: {
    duracao: "26 meses",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788193/Metro/vjhmsxc6imlmdxw7zmuw.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788409/Metro/vsiwixe8onsdd1jl1kny.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788088/Metro/ex7zpugb3uamrxqcm4gb.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788276/Metro/oqt0w3exvx0hythwbfue.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788220/Metro/jnof7mvtubv20rvxu2qb.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787919/Metro/jxslz02nwpfduxbmjvz2.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788305/Metro/anzmzwj877g2h1q3l027.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788240/Metro/ibwiarfpyyrknqiqxmku.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788128/Metro/pho9azstsh6hvq1rucm8.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788153/Metro/ve5lcainlpv7odcciv5b.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788230/Metro/eubifnqsswycgr4svkdp.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788056/Metro/xrtjhswdhnoqfkby2wfg.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787971/Metro/w5brtkmvjnjbg5mc2tul.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788341/Metro/m6ddsq86g9qbvrh1vtsp.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788285/Metro/vtqr4utrua2wdkzadgi8.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787960/Metro/vey38ccsdcckbfgsythi.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788299/Metro/vdolh9zdsutevoin76ti.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788174/Metro/yociiaranjwdigrdoehc.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788359/Metro/yhav9wbo0dfnhs58b0wr.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788168/Metro/cptxxdyrpuq8edfplv3u.jpg",
  ],
  especificacoes: {
    "Área Construída": "9.475,43 m²",
    "N° de UTIs": "N° de UTIs leitos",
    "Centro Cirúrgico": "6 leitos",
    "Sala Vermelho": "3 leitos",
    "Sala Amarela": "4 leitos",
    "Sala de Observação": "12 leitos",
    Outros: ["Ambulatório", "Tomografia", "Raio-X"],
  },
};


export const HospitalRegionalLitoralNorte: ProjetoEngenharia = {
  id: "prj_hospital_regional_litoral_norte",
  categoria: "Hospitais",
  titulo: "Hospital Regional do Litoral Norte - Alagoinhas-BA",
  descricao: "Não Informado",
  descricaoCompleta: "Não Informado",
  status: "Em andamento",
  relevancia: 1,
  cliente: "CONDER",
  localizacao: "Município de Itabuna – Bahia",
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787938/Metro/ltciooxbwrofscfard3l.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788368/Metro/auqljwkbxxbz4h0n6j9o.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788122/Metro/z9excn6yl7gvkggfsk03.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788388/Metro/nm3rnzznhvoxlszpeok0.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788412/Metro/wdxhykoys4f1stkkgppo.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788199/Metro/ewjhagjsneiuzrq1yzvd.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787975/Metro/izwl639tprzta3i26amm.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788207/Metro/annjoonunijbdopkc6jt.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788059/Metro/up5ge4lgifqjij1mafz5.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788059/Metro/up5ge4lgifqjij1mafz5.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788345/Metro/ttfjlyqdnqlpnkrtehrf.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787951/Metro/swznxlmastrdxaakhmm9.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787927/Metro/qak7xor0slybg9mwl5oc.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788260/Metro/tctbkrouxghxo3l9pqr4.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788022/Metro/fv64hcsuewnx7q1amhmt.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788138/Metro/yncssqmibyuzdhypgqhu.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788071/Metro/suv5r4g8hzyadkrbcifd.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788080/Metro/abnvpkzmtcsv7zz9ak4o.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788100/Metro/pn62nqdfrgschjqkva3b.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788333/Metro/ybfqlewnews9u6cda4nv.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787941/Metro/wfthafssy9bkua6d7qsm.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788204/Metro/bwhnl4xoq1vbb7p1voir.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787903/Metro/aefvlmd3ircgmmp4emeh.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788113/Metro/umobdfy1sxo2nhteaan9.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788119/Metro/whtcupw1si7coi4p2kle.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788159/Metro/tduoqxcxtgubvtagzhff.jpg",
  ],
  especificacoes: {
    "Área Construída": "23.262,09m²",
    "N° de UTIs": "30 leitos de UTI",
    "N° de Enfermaria": "150 leitos de Enfermarias",
    "Parto Normal": "3 leitos",
    "Salas de Cirurgia": "5 + 1 de Hemodinâmica",
    "Salas de Imagenologia": "2 Tomógrafos, 2 Raios X, 1 Ressonância",
    Quimioterapia: "12 poltronas",
    Radiologia: "Acelerador Linear e Braquiteriapia",
  },
};


export const HospitalDrJoseBorbaSanta: ProjetoEngenharia = {
  id: "prj_hospital_dr_jose_borba_santa",
  categoria: "Hospitais",
  titulo: "Hospital Dr. José Borba–Santa Maria da Vitória-BA ",
  descricao: "A obra de ampliação do hospital foi concluída com alto padrão de qualidade, contemplando no pavimento térreo a execução de posto de enfermagem, áreas de esterilização, armazenagem, desinfecção química, centro cirúrgico, sala de parto, unidades de tratamento intensivo (UTI), setores de descontaminação e lavagem, além de circulações internas funcionais com rampas de acessibilidade e elevadores interligando os dois pavimentos, em conformidade com as normas técnicas vigentes. ",
  descricaoCompleta: "A obra de ampliação do hospital foi concluída com alto padrão de qualidade, contemplando no pavimento térreo a execução de posto de enfermagem, áreas de esterilização, armazenagem, desinfecção química, centro cirúrgico, sala de parto, unidades de tratamento intensivo (UTI), setores de descontaminação e lavagem, além de circulações internas funcionais com rampas de acessibilidade e elevadores interligando os dois pavimentos, em conformidade com as normas técnicas vigentes. No primeiro pavimento, foram implantadas novas enfermarias, sendo 30 leitos destinados à clínica cirúrgica e outros 30 leitos à clínica geral e psiquiatria, ampliando significativamente a capacidade assistencial da unidade. As intervenções externas incluíram a execução de iluminação, paisagismo, passeios acessíveis, adequação dos acessos ao hospital existente e organização dos estacionamentos, resultando em um complexo hospitalar plenamente funcional, seguro e entregue conforme os projetos aprovados, com elevado padrão técnico e construtivo",
  status: "Concluído",
  relevancia: 1,
  cliente: "PREFEITURA(CONVÊNIO SESAB)",
  localizacao: "Município de Santa Maria da Vitória – BA",
  periodo: {
    duracao: "24 meses",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788415/Metro/fmga8mnuj2tlo2vxe6zp.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788141/Metro/a2i1a5gpku73yft6aawe.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788141/Metro/a2i1a5gpku73yft6aawe.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788110/Metro/xbmqwvbmlijqdrrbalsv.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787906/Metro/mwystbbelyqmuwtjuunj.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788371/Metro/t44uhg7i2n4wrjsstsyl.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788397/Metro/ivt4tardpumbkciw52t9.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788354/Metro/xaml3czcwomdxdaxxx3z.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788135/Metro/jmijxvfeasfjdcc9spsx.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788362/Metro/mlikbyuqhhmfcmhjinqw.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788308/Metro/geupw333zxqtlln6l3zy.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788210/Metro/ojwum0b2v10sd5ak2vub.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788224/Metro/otkwleedgrs6dp26vden.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788351/Metro/bhnrbrpzoaielqije4ud.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788068/Metro/cex2eblozxybdvui6w7i.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788075/Metro/rvtlir4olnng4j5opwih.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788050/Metro/rqrmzj77s85xafixhuvm.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787964/Metro/ghgy9urotmgwa0gdecub.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788288/Metro/fwq0sjqksuotlsrqg0yq.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788253/Metro/khmplfky5loiqm0l00o7.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788403/Metro/gitgsl8y6jelvkip9pzd.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788248/Metro/iszpru0evo0hes3tqb4v.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787911/Metro/tivmqsuosbft22dxeapy.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788162/Metro/duubys0on6il7vpwuz0k.jpg",
  ],
  especificacoes: {
    "Área Construída": "4.662,24m²",
    "N° de UTIs": "10 leitos de UTI",
    "N° de Enfermaria": "60 leitos de Enfermarias",
    "Parto Normal": "3 leitos",
    "Salas de Cirurgia": "5 salas",
  },
};

export const ObrasComplementaresMaternidadeJoaoBatista: ProjetoEngenharia = {
  id: "prj_obras_maternidade_joao_batista",
  categoria: "Hospitais",
  titulo: "Obras complementares maternidade João Batista Caribé Salvador-BA",
  descricao:
    "Este projeto abrange a execução de uma obra hospitalar de alta complexidade, combinando estética moderna e funcionalidade rigorosa.",
  descricaoCompleta:
    "Este projeto abrange a execução de uma obra hospitalar de alta complexidade, combinando estética moderna e funcionalidade rigorosa. O escopo da obra incluiu o acabamento de superfícies metálicas e a instalação de brises em alumínio, garantindo eficiência térmica e design contemporâneo. No âmbito clínico, destaca-se a implementação de blindagens e elementos construtivos de proteção para a sala de Raio-X, além da construção e adequação de ambientes críticos como salas de ultrassonografia (USG), acolhimento, higienização e áreas para instalação de autoclave. A estrutura é complementada por sistemas vitais de engenharia, incluindo uma Central de Gases Medicinais, câmaras frigoríficas e instalações completas de climatização, assegurando um ambiente seguro e tecnicamente otimizado para operações de saúde.",
  status: "Concluído",
  relevancia: 1,
  cliente: "Governo do Estado da Bahia - CONDER",
  localizacao:
    "Av. Afrânio Peixoto (Avenida Suburbana), s/n.- Coutos, Salvador - BA",
  periodo: {
    duracao: "4 meses",
  },
  imagens: [
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788098/Metro/htff3f5jnf9shdm7exx3.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788025/Metro/tbguvjuxmgd6jmoxwpoy.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788312/Metro/psmvd1bltrx6bwnqfxyn.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788400/Metro/daglaxbjoqfdtyq9cezr.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788073/Metro/s8vw6wcjfugfemqjfxel.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787914/Metro/kpvqt8hvc0zvnqimna3l.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788116/Metro/q3mj1mzjszl9cugxnqv6.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788263/Metro/ow7yw3xacbkhghgldhf5.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788156/Metro/bszf2caxetvl4ccwls5e.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788178/Metro/tw32bwds2glibjtepb8f.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788020/Metro/ggjwcd19msojl4jnrvtt.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788104/Metro/mhvo0uypa5lunzyvurzg.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788132/Metro/xki2s1kqza0udadpkgtf.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788265/Metro/faghoy92tztydnyigxhi.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788066/Metro/kbjm3yswt8rp6ypjpujs.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771787985/Metro/nnvwiplt96bepemdwdm9.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788330/Metro/thd5o9zl849gtnx4m394.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788094/Metro/nxk5xvfjzku2qt87y4ab.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788202/Metro/dnojmbg3qjzn56n7tlmq.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788291/Metro/ejv5dy8dexu24yuxx6ox.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788315/Metro/ugzcuvwnyikrw8re01gm.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788018/Metro/lmaajhero31wva4icrs8.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788091/Metro/biizq5phdsn2wtgpxekn.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788374/Metro/ktwno5sxolj1xhy0pnhz.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788365/Metro/sisncjpsofxzmwxglgmp.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788212/Metro/w3j4ftj1ytlh468hlfea.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788235/Metro/to6hd3m3ufmjioos07nt.jpg",
    "https://res.cloudinary.com/dotoe2mkd/image/upload/v1771788268/Metro/r6gp9uxmhslqetih6ure.jpg",
  ],
  especificacoes: {
    "Área ampliada": "440m²",
    "N° de UTI Neonatal": "10 leitos",
  },
};